# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Yet Another Developer Blog
email: tim.wong1992@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A little notebook of my adventures in software engineering; fun problems I
  encounter, discoveries about technologies I use, and progress reports of
  learning new languages/frameworks and personal projects all go here.
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "http://timwong1992.github.io" # the base hostname & protocol for your site
github_username:  timwong1992

# Build settings
markdown: kramdown
